import BusinessInfoForm from "@/src/components/BusinessInforForm";
import StepBar from "@/src/components/StepBar";
import UserInfoForm from "@/src/components/UserInfoForm";
import Head from "next/head";
import Image from "next/image";
import logo from "../src/assets/logo.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Truffles Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" py-4 px-6 flex justify-between items-center border-b-2">
        <div>
          <Image src={logo} />
        </div>
        <div>
          <span>
            Having trouble?{" "}
            <a className=" text-purple" href="">
              Get Help
            </a>
          </span>
        </div>
      </div>
      <div className=" w-full grid md:grid-cols-12">
        <div className=" sm:col-span-12 md:col-span-3">
          <StepBar grid />
        </div>
        <div className=" ml-10 sm:col-span-12 md:col-span-9 ">
          <UserInfoForm />
          {/* <BusinessInfoForm /> */}
        </div>
      </div>
    </>
  );
}
